language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="af709c3ff1eaa66202cee9023b96ae55c2e4df094708c095cd945c761870be8c" --format=php-clover clover.xml
